language: java

sudo: false

jdk:
  - openjdk11

before_install:
  - wget -O jdk-win.zip $JDK_WIN_URL
  - unzip jdk-win.zip
  - pwd
  - ls -al
  - ls -al $JDK_WIN_HOME
  

install:
  - chmod a+x ./gradlew

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  target-branch: images
  local-dir: build/image-zip
  on:
    branch: master

cache:
  directories:
    - $HOME/.gradle

script: ./gradlew --info --stacktrace build jlinkZip
